version: '2'
services:
  storj-mongo:
    image: mongo
    ports:
      - "27017:27017"
  storj-sender:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "10000:10000"
    links:
      - storj-mongo:storj-mongo
